### ISSUE TITLE
Could not close paywall

### ISSUE THREAD

**Issue by al-tush** [adaptyteam/AdaptyUI-Flutter#5]
Could not close paywall by click on X button in iOS.

Logs from xcode: 
```
[Adapty v2.7.0] - VERBOSE: Completed getProfile(_:) [d4rm9Z]  is successful.
[Adapty v2.7.0] - VERBOSE: LifecycleManager: syncProfile Done
[Adapty v2.7.0] - VERBOSE: LifecycleManager: scheduleProfileUpdate after 60.0 sec.
nw_resolver_start_query_timer_block_invoke [C30.1] Query fired: did not receive all answers in time for api.adapty.io:443
```

```
  adapty_flutter:
    version: "2.7.0"
  adapty_ui_flutter:
    version: "2.0.3"

iOS version 17.1
```

**Comment by al-tush** [comment]
The same issue with Android.

```
  adapty_flutter:
    version: "2.7.1"
  adapty_ui_flutter:
    version: "2.0.3"
```

Tap to close do not add useful info to log
Some data from log:
```
V/Adapty_v2.7.0( 9609): VERBOSE: GET https://api.adapty.io/api/v1/sdk/analytics/profiles/34d2d415-362b-41dc-9e86-0ca2a259452b/
V/Adapty_v2.7.0( 9609): VERBOSE: Request is successful. https://api.adapty.io/api/v1/sdk/analytics/profiles/34d2d415-362b-41dc-9e86-0ca2a259452b/ Response:
...
"data":{"type":"adapty_analytics_profile","id":"34d2d415-362b-41dc-9e86-0ca2a259452b","attributes":{"app_id":"7de79a4d-793f-44d5-9a6c-a76f359e6d3d","profile_id":"34d2d415-362b-41dc-9e86-0ca2a259452b","customer_user_id":"d7b155de8274cff9"
```

Probably bug in the Adapty configuration but it looks too easy )

**Comment by x401om** [comment]
Hi, @al-tush, did you implement [paywallViewDidPerformAction](https://docs.adapty.io/docs/paywall-builder-events-flutter#actions) method on the dart side?

**Comment by al-tush** [comment]
Thank you! After i implemented AdaptyUI().addObserver it works good.
Probably the documentation at [Flutter – Handling events](https://docs.adapty.io/docs/paywall-builder-events-flutter) is unclear:
> **If you need to control or monitor** the processes that take place on the purchase screen, you need to implement the AdaptyUIObserver methods and register the observer before presenting any screen

**Comment by al-tush** [comment]
Without any changes on client side paywall stopped closing. No exceptions in logcat.
Adapty method  `Future<dynamic> _handleIncomingMethodCall(MethodCall call)` doesn't call.

Adapty version:
```
  adapty_flutter:
    dependency: "direct main"
    description:
      name: adapty_flutter
      sha256: "0ec4e47608c30b71789521de6856999b0f4488f93fd145c134a71bb0382d72df"
      url: "https://pub.dev"
    source: hosted
    version: "2.7.1"
  adapty_ui_flutter:
    dependency: "direct main"
    description:
      name: adapty_ui_flutter
      sha256: ef9015a17a367922628eeb45d067b4cf7d113a7a309cac7c8318e32b091c9797
      url: "https://pub.dev"
    source: hosted
    version: "2.0.4"
```

Logs:
`V/Adapty_v2.7.0(18163): VERBOSE: UI v2.0.3: #167908197# action: close`
